import timer from './modules/timer';
import menu from './modules/menu';
import momdal from './modules/modal';
import textForm from './modules/textForm';
import tabs from './modules/tabs';
import slider from './modules/slider';
timer('25 february 2022');
menu();
momdal();
textForm();
tabs();
slider();